extends:
  - "eslint:recommended"
  - "plugin:astro/recommended"
  - "plugin:astro/jsx-a11y-recommended"
  - "prettier"
overrides:
  - files:
      - "*.astro"
    parser: "astro-eslint-parser"
    parserOptions:
      parser: "@typescript-eslint/parser"
      extraFileExtensions:
        - ".astro"
